language: csharp  
sudo: required  
mono: none
dotnet: 3.1
services: 
  - docker
before_script:
  - dotnet restore
  - docker-compose up -d --build
script:  
  - dotnet test ./TestHttpTests -c Release
after_success:
  - docker build -t test-http ./TestHttp
  # log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push 
  - docker images
  - docker push l1f33nd3r/test-http-api:test-http