version: '3.4'

services:
  #application:
   # build: ./TestHttp
  #  ports:
  #    - 5000:80
  #    - 5001:443      
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80;https://+:5001;http://+:5000;
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
